package typescript_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/sst/sst/v3/pkg/project/common"
	"github.com/sst/sst/v3/pkg/types/typescript"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func setupProject(t *testing.T, deps map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	pkg := map[string]interface{}{"dependencies": deps}
	data, _ := json.Marshal(pkg)
	os.WriteFile(filepath.Join(dir, "package.json"), data, 0644)
	return dir
}

func TestGenerate(t *testing.T) {
	t.Run("no package.json returns nil", func(t *testing.T) {
		dir := t.TempDir()
		err := typescript.Generate(dir, common.Links{})
		require.NoError(t, err)
	})

	t.Run("creates sst-env.d.ts with types", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"MyBucket": {
				Properties: map[string]interface{}{
					"name": "my-bucket",
					"arn":  "arn:aws:s3:::my-bucket",
				},
			},
		}

		err := typescript.Generate(dir, links)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, "auto-generated by SST")
		assert.Contains(t, out, "\"MyBucket\":")
		assert.Contains(t, out, "\"name\": string")
		assert.Contains(t, out, "\"arn\": string")
	})

	t.Run("number and boolean types", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"Config": {
				Properties: map[string]interface{}{
					"port":    42,
					"rate":    3.14,
					"enabled": true,
				},
			},
		}

		err := typescript.Generate(dir, links)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, "\"port\": number")
		assert.Contains(t, out, "\"rate\": number")
		assert.Contains(t, out, "\"enabled\": boolean")
	})

	t.Run("nested properties", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"Db": {
				Properties: map[string]interface{}{
					"connection": map[string]interface{}{
						"host": "localhost",
					},
				},
			},
		}

		err := typescript.Generate(dir, links)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, "\"connection\": {")
		assert.Contains(t, out, "\"host\": string")
	})

	t.Run("sorted keys", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"Thing": {
				Properties: map[string]interface{}{
					"z": "z",
					"a": "a",
				},
			},
		}

		err := typescript.Generate(dir, links)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		aIdx := indexOf(out, "\"a\"")
		zIdx := indexOf(out, "\"z\"")
		assert.Greater(t, aIdx, -1)
		assert.Less(t, aIdx, zIdx)
	})

	t.Run("type key quoted at top level", func(t *testing.T) {
		dir := setupProject(t, map[string]string{})

		links := common.Links{
			"MyResource": {
				Type: "aws.s3.Bucket",
				Properties: map[string]interface{}{
					"type": "aws.s3.Bucket",
					"name": "bucket",
				},
			},
		}

		err := typescript.Generate(dir, links)
		require.NoError(t, err)

		content, err := os.ReadFile(filepath.Join(dir, "sst-env.d.ts"))
		require.NoError(t, err)

		out := string(content)
		assert.Contains(t, out, "\"type\": \"aws.s3.Bucket\"")
	})

	t.Run("nested package.json", func(t *testing.T) {
		dir := t.TempDir()
		// root package.json
		pkg, _ := json.Marshal(map[string]interface{}{"dependencies": map[string]string{}})
		os.WriteFile(filepath.Join(dir, "package.json"), pkg, 0644)

		sub := filepath.Join(dir, "packages", "web")
		os.MkdirAll(sub, 0755)
		os.WriteFile(filepath.Join(sub, "package.json"), pkg, 0644)

		err := typescript.Generate(dir, common.Links{})
		require.NoError(t, err)

		assert.FileExists(t, filepath.Join(dir, "sst-env.d.ts"))
		assert.FileExists(t, filepath.Join(sub, "sst-env.d.ts"))
	})
}

func indexOf(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
